# Predict Car Prices of different model

In [120]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [121]:
df=pd.read_csv(r"C:\Users\raidi\OneDrive\Desktop\Python\Datasets\carprices.csv")

In [122]:
df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Car Model      13 non-null     object
 1   Mileage        13 non-null     int64 
 2   Sell Price($)  13 non-null     int64 
 3   Age(yrs)       13 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 544.0+ bytes


In [124]:
df["Car Model"]

0                    BMW X5
1                    BMW X5
2                    BMW X5
3                    BMW X5
4                    BMW X5
5                   Audi A5
6                   Audi A5
7                   Audi A5
8                   Audi A5
9     Mercedez Benz C class
10    Mercedez Benz C class
11    Mercedez Benz C class
12    Mercedez Benz C class
Name: Car Model, dtype: object

# Converting catregorial data using OneHotEncoder

In [125]:
from sklearn.preprocessing import LabelEncoder

In [126]:
le=LabelEncoder()

In [127]:
df["Car Model"]=le.fit_transform(df["Car Model"])

In [128]:
df['Car Model']

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     0
8     0
9     2
10    2
11    2
12    2
Name: Car Model, dtype: int32

In [129]:
df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0          1    69000          18000         6
1          1    35000          34000         3
2          1    57000          26100         5
3          1    22500          40000         2
4          1    46000          31500         4

In [130]:
X=df.drop('Sell Price($)',axis=1)
X

Car Model  Mileage  Age(yrs)
0           1    69000         6
1           1    35000         3
2           1    57000         5
3           1    22500         2
4           1    46000         4
5           0    59000         5
6           0    52000         5
7           0    72000         6
8           0    91000         8
9           2    67000         6
10          2    83000         7
11          2    79000         7
12          2    59000         5

In [131]:
y=df['Sell Price($)'].values
y

array([18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000,
       22000, 20000, 21000, 33000], dtype=int64)

In [132]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [133]:
ct=ColumnTransformer([('Car Model',OneHotEncoder(),[0])], remainder="passthrough")

In [134]:
X=ct.fit_transform(X)
X

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [135]:
X=X[:,1:]

In [136]:
from sklearn.model_selection import train_test_split

In [137]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.3)

In [138]:
from sklearn.linear_model import LinearRegression

In [139]:
model=LinearRegression()

In [140]:
model.fit(X_train,y_train)

LinearRegression()

In [141]:
model.predict(X_test)

array([32279.99997743, 11352.0000474 , 22068.00003159, 18744.00002708,
       27767.99997518, 44225.99991084, 30971.99995711, 33347.99995261,
       24767.99997517, 37175.99993905])

In [142]:
y_test

array([33000, 12000, 19300, 20000, 22000, 40000, 31500, 32000, 26100,
       34000], dtype=int64)

In [143]:
model.score(X_test,y_test)

0.8856781879602962

Predict price of merchedez of 4 years old with miliage 4500

In [146]:
price_predict_merchedez=model.predict([[0,1,4500,4]])
price_predict_merchedez

array([63017.99966491])

Predict price of BMW X5 that is 7 years old with miliage 86000

In [149]:
price_predict_BMW=model.predict([[0,0,8600,7]])
price_predict_BMW

array([57825.59954603])